### ISSUE TITLE
Move Tasks from ToDo.md to Issues

### ISSUE THREAD

**Issue by viluon** [viluon/cccitygen#1]
These tasks have to be made into issues:
- [x] Add overloads for Point3D
- [x] What about the constructor chain interface?
- [x] Grid3D should use Point3D for origin
- [x] Rooms are somewhat limited. They can only have 4 walls. What about non-rectangular rooms?
- [x] Grid3D:resize()
- [x] Should room floors be limited only to the inner area (exclude the borders with walls)?
- [x] Move stuff from ToDo to GitHub Issues (done because the ToDo.md file has been deleted and this is in fact an issue :stuck_out_tongue: )
- [x] Implement require(), dofile() is dumb
- [ ] Building should keep a list of outside walls
- [x] IDuplicable?
- [ ] Generalize Palette, add RoomPalette
- [ ] Use RoomPalette in :populate() along with BuildingPopulator or something similar
  - [ ] BuildingPopulator will contain a list of rules such as what Rooms the building should use and how should they be connected, how many of them etc
  - [ ] BuildingPopulators will define Building types, for example a family house vs. mall etc
  - [ ] BuildingPopulators should have a clue about how the building is structured (floors, staircases, elevators?)
- [ ] Rooms should hold the information about windows, Buildings should only link to them

_Note_: The fact that a task here is checked means that it has been made into an issue, it _**doesn't** mean it's **solved**_.
